# Generated by Django 4.2 on 2023-07-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0002_articlerate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlerate",
            name="rate",
            field=models.SmallIntegerField(default=0, verbose_name="rate"),
        ),
    ]
